name: CI Spring Boot Docker
on:
  push:
    branches:
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test15b
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Compilar proyecto
        run: mvn clean package -DskipTests
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}  
      - name: Construir imagen Docker
        run: docker build -t sbstn2006/backend-springboot:latest .
      - name: Publicar imagen en Docker Hub
        run: docker push sbstn2006/backend-springboot:latest
      - name: Verificar JAR generado
        run: ls -la target